lang: cpp
compiler: gcc
os: linux
addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9

install: make get-deps premake4

before_install:
  - premake4 gmake
  - cd build/gmake
  - make
