language: cpp
compiler: gcc
os: linux
matrix:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - wget
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
  - tar -xzvf premake-5.0.0-alpha15-linux.tar.gz
  - chmod +x premake5

script: "./premake5 gmake && cd build/cmake && make"
